FIX using all or none
When passing a query with `Model.all` or `Model.none`, we get a
`NoMethodError: undefined method 'or' for nil:NilClass` due to not
constraints being set by arel.
Fixed by modifying original query to use `where('0=1')` or
`where('1=1')`.

Rel #22